### ISSUE TITLE
Partners page partners should be expandable

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/climatehub#70]
### Acceptance Criteria:
* Partners grid should be clickable and expandable

**Comment by vinielk** [comment]
Took me about 10 hours to finish this ticket (including code changes, testing on mobile/desktop/different browsers and pushing changes to production). I had to redo the partners grid without using bootstrap because it didn't work the way I wanted it to. I think this solution is better than the implementation we have on other sites that do the same thing (i.e. CTC website, PIE website).
